volumes:
  model_cache:

services:
  speech-io-server:
    image: ghcr.io/l4b4r4b4b4/speech-io-server:latest
    ports:
      - 8003:8003
    volumes:
      - model_cache:/app/model_cache
      - ./app/reference_audio:/app/reference_audio
      - ./app/outputs:/app/outputs
      - ./app/voices:/app/voices
      - ./app/config.yaml:/app/config.yaml:rw
    devices:
      - nvidia.com/gpu=all
    device_cgroup_rules:
      - "c 195:* rmw"
      - "c 236:* rmw"
    # deploy: thhis is considered legacy, same as setting `runtime: nvidia`
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HF_HUB_ENABLE_HF_TRANSFER=1
